const plantsData = [
  {
    id: "0",
    name: "Tomato",
    health: "95",
    waterLevel: "90",
    humidity: "47",
    light: "78",
    pHLevel: "6.5 pH",
    soil: "78",
    seed: "Hybrid",
    planter: "brown",
    imgUrl: "tomato.png",
  },
  {
    id: "1",
    name: "Cilantro",
    health: "92",
    waterLevel: "90",
    humidity: "47",
    light: "78",
    pHLevel: "6.5 pH",
    soil: "78",
    seed: "Hybrid",
    planter: "brown",
    imgUrl: "tomato.png",
  },
  {
    id: "2",
    name: "Mint",
    health: "91",
    waterLevel: "90",
    humidity: "47",
    light: "78",
    pHLevel: "6.5 pH",
    soil: "78",
    seed: "Hybrid",
    planter: "brown",
    imgUrl: "tomato.png",
  },
  {
    id: "3",
    name: "Pepper",
    health: "85",
    waterLevel: "90",
    humidity: "47",
    light: "78",
    pHLevel: "6.5 pH",
    soil: "78",
    seed: "Hybrid",
    planter: "brown",
    imgUrl: "tomato.png",
  },
  {
    id: "4",
    name: "Spinach",
    health: "91",
    waterLevel: "90",
    humidity: "47",
    light: "78",
    pHLevel: "6.5 pH",
    soil: "78",
    seed: "Hybrid",
    planter: "brown",
    imgUrl: "tomato.png",
  },
];

export default plantsData;
